language: python
python:
  - "2.7"

# install system dependencies here with apt-get. 
before_install:
  - sudo ./provision/debian.sh

# install python dependencies including this package in the travis
# virtualenv
install:
  - ./provision/python.sh

# command to run tests, e.g. python setup.py test
script:
  - nosetests --with-coverage --cover-package=textract
  - pep8 textract/ bin/textract
  - cd docs && make html

# commands to run after the tests successfully complete
after_success:
  - coveralls
